name: "Sample Workflow"
on:
  workflow_dispatch:
    
jobs:
    run_edge:
        name: Test
        runs-on: test-runner
        
        steps:
        - name: Run Hello World
          run: echo "Hello World1"
