name: "Sample Workflow"
on:
  workflow_dispatch:
    
jobs:
    run_edge:
        name: Test
        runs-on: any
        
        steps:
        - name: Run Hello World
          run: echo "mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin"
