name: "Run edge project"
on:
  workflow_dispatch:
    
jobs:
    run_edge:

        strategy:
            fail-fast: false
        
        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '10.x'
        - name: Install Dependencies
          run: npm install
        - run: node sample-edge.js


